### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by toprakkaya** [iyzico/iyzipay-laravel#19]
`composer require iyzico/iyzipay-laravel dev-master` command not working. 
But `composer require actuallymab/iyzipay-laravel dev-master` is working.
I think, you have to update configuration of package at packagist.org.

**Comment by actuallymab** [comment]
Yes iyzico will handle this ASAP

**Comment by sotuzun** [comment]
We updated the package in packagist. You can install it now.

`composer require iyzico/iyzipay-laravel`
