### ISSUE TITLE
laravel 5.2

### ISSUE THREAD

**Issue by BesimVatan** [iyzico/iyzipay-laravel#21]
Merhaba, paket laravel 5.2 sürümünü desteklemiyor mu acaba? 
Mevcut sistemde kullandığım 5.2 versiyonuna paketi entegre edemedim. 
Localde  5.4 versiyonu kurup ona entegre etmeyi denediğimde ise hiç bir sorun yaşamadım. 
5.2 için bir çözüm öneriniz var mıdır?

**Comment by actuallymab** [comment]
@BesimVatan tam olarak hangi adimda sikinti yasadiginizi detaylariyla yazabilir misiniz?

**Comment by BesimVatan** [comment]
Oncelikle Teşekkür ederim,
5.2 de loadMigrationsFrom komutu yokmus. 5.3 ile gelmiş bu komut.
Ben providerlari ekledikten sonra vendor publish kisminda
BadmethodCallException loadmigrationfrom hatasi aliyorum.

29 Haz 2017 00:48 tarihinde "Mehmet Aydin Bahadir" <notifications@github.com>
yazdı:

@BesimVatan <https://github.com/besimvatan> tam olarak hangi adimda sikinti
yasadiginizi detaylariyla yazabilir misiniz?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iyzico/iyzipay-laravel/issues/21#issuecomment-311801864>,
or mute the thread

**Comment by actuallymab** [comment]
Bu sikintiyi yasamaya devam ediyor iseniz lutfen `help-wanted` labeli ile yeni bir issue aciniz.
