### ISSUE TITLE
php ~7.0 -> your PHP version (5.6.30) does not satisfy that requirement

### ISSUE THREAD

**Issue by metadelete** [iyzico/iyzipay-laravel#23]
Merhaba Laravel 5.4 (php v 5.6) üzerinde çalışıyorum, composer yükleme aşamasında şu problemi alıyorum, 

  Problem 1
    - Installation request for iyzico/iyzipay-laravel dev-master -> satisfiable by iyzico/iyzipay-laravel[dev-master].
    - iyzico/iyzipay-laravel dev-master requires php ~7.0|~7.1 -> your PHP version (5.6.30) does not satisfy that requirement.

**Comment by vjolenz** [comment]
Composer.json da gereksinim olarak en dusuk php versiyonu 7.0 olarak belirtilmis ve sizin surumunuz 5.6 oldugu icin hata almaktasiniz. PHP versiyonunuzu yukseltirseniz herhangi bir problemle karsilasmazsiniz

**Comment by metadelete** [comment]
Php versiyonunu guncellemem mumkun degil. Bu repoda php 7 yi gerektiren bir dependency goremedim.

**Comment by vjolenz** [comment]
Detayli bakmadim ama bende goremedim. `composer install --ignore-platform-reqs` olarak yukleyip deneyin bir?

**Comment by actuallymab** [comment]
https://github.com/iyzico/iyzipay-laravel/blob/master/src/IyzipayLaravel.php#L52 ?
