### ISSUE TITLE
Class 'Iyzico\IyzipayLaravel\IyzipayLaravelServiceProvider' not found

### ISSUE THREAD

**Issue by FrancescoMussi** [iyzico/iyzipay-laravel#30]
Hello. Is the package still active?

I have followed the installation docs but I am getting this error:

```
In ProviderRepository.php line 208:             
  Class 'Iyzico\IyzipayLaravel\IyzipayLaravelServiceProvider' not found  
```

Laravel version: 5.6

Do you know why this is happening?

Thanks!

**Comment by EnverKESMEN** [comment]
Did you try "composer dump-autoload"?

**Comment by FrancescoMussi** [comment]
Thanks for replying.
There was probable something wrong.

I have run: `composer dump-autoload`
I have updated php version to latest (7.2.9)
Clean up the project
Run composer update
Then install again `iyzipay-laravel` and it was installed correctly.

**Comment by WebStudio523** [comment]
I have run "Composer dump-autoload" command, but same error occured.
First I run composer require iyzico/iyzipay-laravel and added service provider config/app.php file.
Can you help me?

**Comment by Smokietr** [comment]
I had the same problem. I saw that Namespace address changed.

`\Actuallymab\IyzipayLaravel\IyzipayLaravelServiceProvider::class,`
`\Actuallymab\IyzipayLaravel\IyzipayLaravelFacade::class`
