### ISSUE TITLE
Class 'Iyzico\IyzipayLaravel' not found

### ISSUE THREAD

**Issue by FrancescoMussi** [iyzico/iyzipay-laravel#31]
I am trying to create subscription plans.
I am following the docs.

I have done this:

```
public function register()
{
    \IyzipayLaravel::plan('yearly-plan', 'Yearly Plan')->yearly()->trialDays(30)->price(1000);
    \IyzipayLaravel::plan('monthly-plan', 'Monthly Plan')->trialDays(30)->price(100);
}
```

But it gives the following error:

`Class iyzipay-laravel does not exist`

I have tried with some workarounds like:

`\Iyzico\IyzipayLaravel::plan()`
or
`app(\IyzipayLaravel::class)::plan()`
or adding `use Iyzico\IyzipayLaravel;` at the top, but without success.

Do you know how can I fix it?
Everything else is working so far, registering user bill_fields, addCreditCard to the user.

**Comment by EnverKESMEN** [comment]
Can you try this steps in your `app/Providers/AppServiceProvider.php` file

1- Add this to the top of the file
`use Iyzico\IyzipayLaravel\IyzipayLaravelFacade as IyzipayLaravel;`

2- Try this register method  
`public function register()
{
    IyzipayLaravel::plan('yearly-plan', 'Yearly Plan')->yearly()->trialDays(30)->price(1000);
    IyzipayLaravel::plan('monthly-plan', 'Monthly Plan')->trialDays(30)->price(100);
}
`
My local development environment is not ready now so I can not try. Let me know if it does not work.

**Comment by FrancescoMussi** [comment]
Thanks for replying.

By doing that I was getting the following error:
`Class iyzipay-laravel does not exist`

But anyway the solution was very close.
It worked for me by using:
`use Iyzico\IyzipayLaravel\IyzipayLaravel;`
instead of
`use Iyzico\IyzipayLaravel\IyzipayLaravelFacade as IyzipayLaravel;`

Should it be included in the docs probably?

**Comment by FrancescoMussi** [comment]
The same applied for subscribing a user to a plan:

```
use Iyzico\IyzipayLaravel\IyzipayLaravel;

$user->subscribe(IyzipayLaravel::findPlan('yearly-plan'));
```
