### ISSUE TITLE
Cannot locate .stub files for migration

### ISSUE THREAD

**Issue by ozgurkadarozgur** [iyzico/iyzipay-laravel#35]
I run the command below
php artisan vendor:publish --provider="Iyzico\IyzipayLaravel\IyzipayLaravelServiceProvider"

and I get this error

Can't locate path: </home/ozgur/Desktop/workspace/laravel-workspace/iyzico/vendor/iyzico/iyzipay-laravel/src/../database/migrations/add_billable_fields.stub>
Can't locate path: </home/ozgur/Desktop/workspace/laravel-workspace/iyzico/vendor/iyzico/iyzipay-laravel/src/../database/migrations/create_credit_cards_table.php.stub>
Can't locate path: </home/ozgur/Desktop/workspace/laravel-workspace/iyzico/vendor/iyzico/iyzipay-laravel/src/../database/migrations/create_subscriptions_table.php.stub>
Can't locate path: </home/ozgur/Desktop/workspace/laravel-workspace/iyzico/vendor/iyzico/iyzipay-laravel/src/../database/migrations/create_transactions_table.php.stub>

**Comment by egulhan** [comment]
I wrote a fix for that [FIX iyzico#35](https://github.com/iyzico/iyzipay-laravel/issues/35). If they want to PR for it, I'll do it.

**Comment by alibaraneser** [comment]
> I wrote a fix for that [FIX iyzico#35](https://github.com/egulhan/iyzipay-laravel/commit/5b16ddcb37e0d5d09fd8e15e3d147c12eefb3328). If they want to PR for it, I'll do it.

Hey @egulhan,

I'm getting this error and don't understand to your solution. Would you like to explain detail?

**Comment by egulhan** [comment]
> > I wrote a fix for that [FIX iyzico#35](https://github.com/egulhan/iyzipay-laravel/commit/5b16ddcb37e0d5d09fd8e15e3d147c12eefb3328). If they want to PR for it, I'll do it.
> 
> Hey @egulhan,
> 
> I'm getting this error and don't understand to your solution. Would you like to explain detail?

You should manually copy iyzipay-laravel's database migration tables into your main database/migrations directory. And run `php artisan migrate`

About my [FIX iyzico#35](https://github.com/egulhan/iyzipay-laravel/commit/5b16ddcb37e0d5d09fd8e15e3d147c12eefb3328), when you run this command 
`php artisan vendor:publish --provider="Iyzico\IyzipayLaravel\IyzipayLaravelServiceProvider"`
it can not find its migration files because it looks for migration files without timestamp but these files actually have timestamp prefix.

**Comment by ImpossibleChicken** [comment]
@egulhan   so did I. ??

Can't locate path: <C:\Courses\LaravelEcommerce\Project-Test\vendor\iyzico\iyzipay-laravel\src/../database/migrations/add_billable_fields.stub>

Copied File [\vendor\iyzico\iyzipay-laravel\database\migrations\create_credit_cards_table.php.stub] To [\database\migrations\2019_10_19_205659_create_credit_cards_table.
php]

Copied File [\vendor\iyzico\iyzipay-laravel\database\migrations\create_subscriptions_table.php.stub] To [\database\migrations\2019_10_19_205659_create_subscriptions_tabl
e.php]

Copied File [\vendor\iyzico\iyzipay-laravel\database\migrations\create_transactions_table.php.stub] To [\database\migrations\2019_10_19_205659_create_transactions_table.
php]
Publishing complete.

**Comment by ImpossibleChicken** [comment]
> 
> 
> @egulhan what is the problem ??
> why tutorial install and rec video ?
> 
> Can't locate path: <C:\Courses\LaravelEcommerce\Project-Test\vendor\iyzico\iyzipay-laravel\src/../database/migrations/add_billable_fields.stub>
> 
> Copied File [\vendor\iyzico\iyzipay-laravel\database\migrations\create_credit_cards_table.php.stub] To [\database\migrations\2019_10_19_205659_create_credit_cards_table.
> php]
> 
> Copied File [\vendor\iyzico\iyzipay-laravel\database\migrations\create_subscriptions_table.php.stub] To [\database\migrations\2019_10_19_205659_create_subscriptions_tabl
> e.php]
> 
> Copied File [\vendor\iyzico\iyzipay-laravel\database\migrations\create_transactions_table.php.stub] To [\database\migrations\2019_10_19_205659_create_transactions_table.
> php]
> Publishing complete.

[add_billable_fields.php.stub]  file rename [add_billable_fields.stub] and problem solved thank you....

**Comment by FatihKaya-kafgame** [comment]
I can't understand, how can i fix this error, I copied manually but not migrate again

**Comment by egulhan** [comment]
I just removed the date prefix from migration files. You can do it manually or you can use our my fix here: https://github.com/egulhan/iyzipay-laravel/commit/5b16ddcb37e0d5d09fd8e15e3d147c12eefb3328

**Comment by FatihKaya-kafgame** [comment]
okey now fixed, deleted migrations path and fixed :)
