### ISSUE TITLE
saving client credit cards on database? do you really do that?

### ISSUE THREAD

**Issue by hayreddintuzel** [iyzico/iyzipay-laravel#37]
I noticed that you are saving cc information on the database. I know this feature is optional, but it is an official iyzico package. And, you know that saving CC information DB is extremely insecure. Many inexperienced users may have to use this option. 

And I know you can keep credit card information on your side. Moreover, you offer it as a paid service. Please remove this feature from the this package and encourage people to use your service. It is a better option for you and community.

**Comment by mehmetselim** [comment]
Hi @hayreddintuzel 

 iyzico response does not send card information. Also, in library only bin number and token info inserted in the database.

Migration: "CreateCreditCardsTable" Details

             $ Table-> increments ( 'id');
             $ Table-> string ( 'billable_id') -> index ();
             $ table-> string ('alias', 100);
             $ table-> string ('number', 10); -> * "bin number field" 
             $ Table-> string ( 'token');
             $ table-> unique (['billable_id', 'token']);
             $ Table-> string ( 'bank') -> nullable ();
             $ Table-> timestamps ();

IyzipayLaravel "addCreditCard" Details
         $ creditCardModel = new CreditCard ([
             'alias' => $ card-> getCardAlias (),
             'number' => $ card-> getBinNumber (),  -> * response "bin number" 
             'token' => $ card-> getCardToken (),
             'bank' => $ card-> getCardBankName ()
         ]);
      $ Payable-> creditcards () -> save ($ creditcardmodel);

Thank you for your attention.

**Comment by hayreddintuzel** [comment]
Yes, you are right. it was my mistake. 
Also, thank you very much for contacting me and discussing this issue. I think I opened the issue without much research.
