### ISSUE TITLE
Thanks for replying.

### ISSUE THREAD

**Issue by dev828** [iyzico/iyzipay-laravel#38]
Thanks for replying.
There was probably something wrong in my project.

I have run: `composer dump-autoload`
I have updated php version to latest (7.2.9)
Clean up the project
Run composer update
Then install again `iyzipay-laravel` and it was installed correctly.

_Originally posted by @FrancescoMussi in https://github.com/iyzico/iyzipay-laravel/issues/30#issuecomment-416512016_

**Comment by WebStudio523** [comment]
I have tried all the process, but the same error happened.

**Comment by alisanalacam** [comment]
what is your version.
dev-master or 1.0.0-alpha.0.

I had the same problem.
first I added the package name to composer.json and i run the composer install command

**Comment by ShopskaSalad** [comment]
The topic has closed as there are no further updates.
